import type { Item } from '@/types';

export const MOCK_ITEMS: Item[] = [
  {
    id: 'gb-001',
    title: "Levi's 501 Vintage 90s Wash",
    brand: "Levi's",
    price: 185,
    currency: 'USD',
    images: ['https://picsum.photos/seed/gb001/600/800'],
    marketplace: 'Grailed',
    marketplaceUrl: 'https://www.grailed.com',
    sellerCountry: '🇺🇸 USA',
    size: 'W32 L32',
    condition: 'Good',
    era: '90s',
    tags: ['denim', 'jeans', 'vintage', 'levis', '501', '90s'],
    description: 'Authentic vintage Levi\'s 501 from the early 90s. Original fit, classic wash, minor fading consistent with age.',
    sku: 'LV-501-90-032',
  },
  {
    id: 'gb-002',
    title: 'Nike Air Max 95 OG Neon',
    brand: 'Nike',
    price: 420,
    currency: 'USD',
    images: ['https://picsum.photos/seed/gb002/600/800'],
    marketplace: 'eBay',
    marketplaceUrl: 'https://www.ebay.com',
    sellerCountry: '🇯🇵 Japan',
    size: 'US 10',
    condition: 'Very Good',
    era: '90s',
    tags: ['nike', 'sneakers', 'air max', '95', 'neon', 'og', '90s'],
    description: 'Rare OG colorway Nike Air Max 95 Neon sourced from a Japanese collector. Minimal creasing, sole in excellent shape.',
    sku: 'NK-AM95-NEO-10',
  },
  {
    id: 'gb-003',
    title: 'Comme des Garçons Homme Plus AW2001 Jacket',
    brand: 'Comme des Garçons',
    price: 1250,
    currency: 'USD',
    images: ['https://picsum.photos/seed/gb003/600/800'],
    marketplace: 'Vestiaire',
    marketplaceUrl: 'https://www.vestiairecollective.com',
    sellerCountry: '🇫🇷 France',
    size: 'M',
    condition: 'Excellent',
    era: 'Y2K',
    tags: ['comme des garcons', 'cdg', 'archive', 'designer', 'jacket', 'y2k'],
    description: 'Archive Comme des Garçons Homme Plus jacket from AW2001. Signature deconstructed silhouette. French provenance.',
    sku: 'CDG-HP-AW01-JAK',
  },
  {
    id: 'gb-004',
    title: 'Maison Margiela MM6 Artisanal Coat',
    brand: 'Maison Margiela',
    price: 890,
    currency: 'USD',
    images: ['https://picsum.photos/seed/gb004/600/800'],
    marketplace: '1stDibs',
    marketplaceUrl: 'https://www.1stdibs.com',
    sellerCountry: '🇮🇹 Italy',
    size: 'S/M',
    condition: 'Very Good',
    era: '2010s',
    tags: ['margiela', 'mm6', 'coat', 'archive', 'designer', 'artisanal'],
    description: 'MM6 Maison Margiela artisanal coat with signature exposed stitching and deconstructed tailoring. Originally purchased in Milan.',
    sku: 'MM6-ART-COT-SM',
  },
  {
    id: 'gb-005',
    title: 'Raf Simons Consumed Bomber Jacket',
    brand: 'Raf Simons',
    price: 2100,
    currency: 'USD',
    images: ['https://picsum.photos/seed/gb005/600/800'],
    marketplace: 'Grailed',
    marketplaceUrl: 'https://www.grailed.com',
    sellerCountry: '🇧🇪 Belgium',
    size: '46',
    condition: 'Good',
    era: '90s',
    tags: ['raf simons', 'bomber', 'consumed', 'archive', 'designer', '90s'],
    description: 'Iconic Raf Simons Consumed era bomber jacket from the late 90s collections.',
    sku: 'RS-CON-BOM-46',
  },
  {
    id: 'gb-006',
    title: 'Stone Island Shadow Project Technical Jacket',
    brand: 'Stone Island',
    price: 640,
    currency: 'USD',
    images: ['https://picsum.photos/seed/gb006/600/800'],
    marketplace: 'Vinted',
    marketplaceUrl: 'https://www.vinted.com',
    sellerCountry: '🇬🇧 UK',
    size: 'L',
    condition: 'Very Good',
    era: '2010s',
    tags: ['stone island', 'shadow project', 'technical', 'jacket', 'outerwear'],
    description: 'Stone Island Shadow Project technical jacket in Garment Dyed Crinkle Reps nylon. Ghost patch intact.',
    sku: 'SI-SP-JAK-L',
  },
  {
    id: 'gb-007',
    title: 'Helmut Lang AW98 Bondage Trousers',
    brand: 'Helmut Lang',
    price: 780,
    currency: 'USD',
    images: ['https://picsum.photos/seed/gb007/600/800'],
    marketplace: 'Vestiaire',
    marketplaceUrl: 'https://www.vestiairecollective.com',
    sellerCountry: '🇦🇹 Austria',
    size: 'W28',
    condition: 'Good',
    era: '90s',
    tags: ['helmut lang', 'bondage', 'trousers', 'archive', '90s', 'designer'],
    description: 'Archive Helmut Lang bondage trousers from AW98. Austrian origin. Strap detailing intact.',
    sku: 'HL-AW98-BND-28',
  },
  {
    id: 'gb-008',
    title: 'CP Company Goggle Jacket SS2003',
    brand: 'CP Company',
    price: 550,
    currency: 'USD',
    images: ['https://picsum.photos/seed/gb008/600/800'],
    marketplace: 'eBay',
    marketplaceUrl: 'https://www.ebay.com',
    sellerCountry: '🇮🇹 Italy',
    size: '50',
    condition: 'Good',
    era: 'Y2K',
    tags: ['cp company', 'goggle', 'jacket', 'mille miglia', 'y2k', 'archive'],
    description: 'CP Company Mille Miglia goggle jacket from SS2003. Original lenses functional. Garment dyed khaki.',
    sku: 'CPC-MM-GOG-50',
  },
  {
    id: 'gb-009',
    title: 'Polo Ralph Lauren Purple Label Suit',
    brand: 'Ralph Lauren',
    price: 480,
    currency: 'USD',
    images: ['https://picsum.photos/seed/gb009/600/800'],
    marketplace: 'Depop',
    marketplaceUrl: 'https://www.depop.com',
    sellerCountry: '🇺🇸 USA',
    size: '40R',
    condition: 'Very Good',
    era: '90s',
    tags: ['ralph lauren', 'purple label', 'suit', 'vintage', 'preppy', '90s'],
    description: 'Polo Ralph Lauren Purple Label two-button suit from early 90s. Italian fabric, hand-stitched lapels.',
    sku: 'RL-PL-SUT-40R',
  },
  {
    id: 'gb-010',
    title: 'Issey Miyake Pleats Please Set',
    brand: 'Issey Miyake',
    price: 390,
    currency: 'USD',
    images: ['https://picsum.photos/seed/gb010/600/800'],
    marketplace: 'Vestiaire',
    marketplaceUrl: 'https://www.vestiairecollective.com',
    sellerCountry: '🇯🇵 Japan',
    size: '3',
    condition: 'Excellent',
    era: '90s',
    tags: ['issey miyake', 'pleats please', 'set', 'archive', 'japanese', 'designer'],
    description: 'Issey Miyake Pleats Please top and pants set in iridescent blue. Japanese origin.',
    sku: 'IM-PP-SET-3',
  },
  {
    id: 'gb-011',
    title: 'Acne Studios Mohair Oversized Cardigan',
    brand: 'Acne Studios',
    price: 295,
    currency: 'USD',
    images: ['https://picsum.photos/seed/gb011/600/800'],
    marketplace: 'Depop',
    marketplaceUrl: 'https://www.depop.com',
    sellerCountry: '🇸🇪 Sweden',
    size: 'S',
    condition: 'Excellent',
    era: '2010s',
    tags: ['acne studios', 'mohair', 'cardigan', 'scandinavian', 'knitwear'],
    description: 'Acne Studios archive mohair blend cardigan in oversized fit. Swedish origin. Original tags attached.',
    sku: 'AS-MOH-CAR-S',
  },
  {
    id: 'gb-012',
    title: "Yohji Yamamoto Y's Asymmetric Wool Dress",
    brand: 'Yohji Yamamoto',
    price: 860,
    currency: 'USD',
    images: ['https://picsum.photos/seed/gb012/600/800'],
    marketplace: '1stDibs',
    marketplaceUrl: 'https://www.1stdibs.com',
    sellerCountry: '🇯🇵 Japan',
    size: '2',
    condition: 'Very Good',
    era: '90s',
    tags: ["yohji yamamoto", "ys", "dress", "asymmetric", "japanese", "designer", "avant-garde"],
    description: "Y's by Yohji Yamamoto asymmetric hem wool dress from mid-90s collection.",
    sku: 'YY-YS-DRS-2',
  },
];
